version: '3.9'

services:
  postgres:
    container_name: tasks_docker
    image: bitnami/postgresql:latest
    ports:
      - '5431:5432'
    environment:
      - POSTGRES_USER=postgre
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=tasks_db
    volumes:
      - tasks_pg_data:/bitnami/postgresql

volumes:
  tasks_pg_data: